Sourcefile := akku.cpp akku.h drohne.cpp drohne.h position.cpp position.h testbench.cpp
Binaryfile := liste

all: compile run

compile:
	g++ -Wall -o $(Binaryfile)  $(Sourcefile)
run:
	./$(Binaryfile)